services:
  python-app:
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install Flask requests && 
      python AD_Registry.py 0.0.0.0:2222"
    ports:
      - 2222:2222

  python-app2:
    image: python:3.9-slim
    volumes:
      - .:/app2
    working_dir: /app2
    command: >
      sh -c "apt-get update && apt-get install -y python3-pip &&
      pip install Flask requests colorama kafka-python cryptography colorama && 
      python AD_Engine.py 0.0.0.0:3333 0.0.0.0:1111 172.27.173.211:9093"
    ports:
      - 3333:3333

    stdin_open: true # Añadir esta línea
    tty: true        # Añadir esta línea